// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAILeINR3H8uu4dDq4MtdMNleD5wCfpPZ8',
    appId: '1:937982991285:web:6e53524aae27ad641ed7fc',
    messagingSenderId: '937982991285',
    projectId: 'ecommerce-b1ee6',
    authDomain: 'ecommerce-b1ee6.firebaseapp.com',
    storageBucket: 'ecommerce-b1ee6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUcTneVk0Kes0wQ83M9IH9L4sSohTjMIE',
    appId: '1:937982991285:android:6b35d6c999ac6a081ed7fc',
    messagingSenderId: '937982991285',
    projectId: 'ecommerce-b1ee6',
    storageBucket: 'ecommerce-b1ee6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj8NBwafipzBqM3ziafpyY7sKOppPkyHE',
    appId: '1:937982991285:ios:932eda6f585eeb0c1ed7fc',
    messagingSenderId: '937982991285',
    projectId: 'ecommerce-b1ee6',
    storageBucket: 'ecommerce-b1ee6.appspot.com',
    iosClientId: '937982991285-g2t6gghe9gi2pcbl0oo49lejrur1nh0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj8NBwafipzBqM3ziafpyY7sKOppPkyHE',
    appId: '1:937982991285:ios:932eda6f585eeb0c1ed7fc',
    messagingSenderId: '937982991285',
    projectId: 'ecommerce-b1ee6',
    storageBucket: 'ecommerce-b1ee6.appspot.com',
    iosClientId: '937982991285-g2t6gghe9gi2pcbl0oo49lejrur1nh0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2',
  );
}
